### PR TITLE
Reorder references based on summary and improve UX of Search mode and Summary mode

### PR DESCRIPTION
**Pull request by cjcenizal**
Replaces https://github.com/vectara/vectara-answer/pull/49

Fixes https://github.com/vectara/vectara-answer/issues/48

This PR also upgrades VUI.

Todo:
- [x] Refine UX of fetching results and then summary when in Summary mode. Surface status, e.g. “Search for references” -> “References retrieved, summarizing”. Gracefully handle subsequent requests.

Deferred:
- [ ] In Summary mode, emphasize linked content over snippet.
- [ ] Dedupe search results (https://github.com/vectara/vectara-answer/pull/47).

### Summary UX

image

image

### Search UX

image

### CODE REVIEW

**Comment by ofermend** [comment]
Hey @cjcenizal - any updates on this one?

**Review by 3eif — APPROVED** [review]
The new UX looks great. Thanks CJ

**Comment by 3eif** [comment]
Also what are the ovals next to the links in the search references shown in the screenshot? I don't see them when running vectara answer

**Comment by cjcenizal** [comment]
> Also what are the ovals next to the links in the search references shown in the screenshot? I don't see them when running vectara answer

That's a glitch caused by the absence of filters. We should fix that in another PR to not render that bit of the UI when filters are missing.

**Comment by ofermend** [comment]
Looks great! How fast can we fix the ovals with a new PR? I don't want to merge into main without it, but I do want to merge to main soon since it looks so nice :)

**Comment by cjcenizal** [comment]
> How fast can we fix the ovals with a new PR?

This is an existing bug so don't need to block the merge on this. I'll fix this in another PR.

**Pull request merged**
